name: sport_plus
description: "Sport tracking app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  image_cropper: ^11.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  cached_network_image: ^3.4.0
  numberpicker: ^2.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^6.0.0
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.5
  path_provider: ^2.1.3
  flutter_file_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

